### ISSUE TITLE
Rake task to create retention policies

### ISSUE THREAD

**Issue by dongshu2013** [avvo/influxdb_setup#5]
Is there a rake task to create retention policies?

**Comment by dplummer** [comment]
Nope. I'm not sure if it's possible to create them via the API?

**Comment by dongshu2013** [comment]
The latest influxdb ruby driver does have the api to retention policy. Check the [Retention Policies Section](https://github.com/influxdata/influxdb-ruby). It will be great to have this feature be enabled.

**Comment by dongshu2013** [comment]
Hey, I added the code to add create_retention_policy task to your gem. I cannot commit in your repo directly so I did these changes in my forked repo. Do you mind to take a look at the code changes https://github.com/dongshu2013/influxdb_setup/pull/1 ? Thanks.

**Comment by dplummer** [comment]
You should be able to create a Pull Request from your branch to avvo/influxdb_setup. That way I can comment on it and track it from this repo.

I'd like to see the README updated with usage of the new config.

**Comment by dongshu2013** [comment]
Here you go https://github.com/avvo/influxdb_setup/pull/6

**Comment by dplummer** [comment]
Released version 1.1 with this support. Thanks!
